#-----------------------------------environment args-----------------------------------
graph_index: 2  # graph index
graph_name: "default_graph"
T: 20  # time horizon
#budget_ratio: 0.06 #', dest='budget_ratio', type=float, default=0.06, help='budget ratio; do the math: budget at each step = graph_size*budget_ratio/T')
budget: 5  # budget at each main step
propagate_p: 0.1  # influence propagation probability
l: 0.05  # influence of each neighbor in LT cascade
d: 1  # d in SC cascade
q: 1  # probability of invited node being present
cascade: 'IC'  # cascade model
greedy_sample_size: 500  # sample size for value estimation of greedy algorithms
